version: "3"
services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./swagger-ui:/usr/share/nginx/html # Replace with the actual path to your Swagger UI files
  backend:
    image: my-backend-image
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
    environment:
      - HTTP_PORT=${HTTP_PORT}
      - HTTP_HOST=${HTTP_HOST}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    # Other service configuration...
  # db:
  #   image: postgres
  #   environment:
  #     - POSTGRES_HOST_AUTH_METHOD=trust
  #     - POSTGRES_DB=${DB_NAME}
  #     - POSTGRES_USER=${DB_USER}
  #     - POSTGRES_PASSWORD=${DB_PASSWORD}
  #   # Other service configuration...
  # kafka:
  #   image: confluentinc/cp-kafka
  #   ports:
  #     - ${KAFKA_PORT}:9092
  #   environment:
  #     - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:${KAFKA_PORT}
  #     - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
  #   depends_on:
  #     - zookeeper

  # zookeeper:
  #   image: confluentinc/cp-zookeeper
  #   ports:
  #     - 2181:2181
