import { shortwaitsApi } from "../shortwaits-api";

export const {
  usePrefetch,

  //Mutations hooks
  useRegisterBusinessMutation,
  useSocialSignInMutation,
  useSocialSignUpMutation,
  useLocalSignUpMutation,
  useLocalSignInMutation,
  useLocalSignOutMutation,
  useUpdateBusinessMutation,
  useCreateBusinessLocalClientsMutation,
  useDeleteBusinessLocalClientsMutation,
  useUpdateBusinessLocalClientMutation,
  useCreateBusinessUserMutation,
  useUpdateBusinessUserMutation,
  useDeleteBusinessUserMutation,
  useUpdateServiceMutation,
  useCreateServiceMutation,
  useDeleteServiceMutation,
  useUploadImageFileMutation,
  useAddBusinessClientMutation,
  // business event mutations
  useCreateBusinessEventMutation,
  useUpdateBusinessEventMutation,
  useUpdateClientsInBusinessEventMutation,
  useUpdateBusinessEventStatusMutation,

  //Query hooks
  useGetAdminMobileQuery,
  useGetAllBusinessClientsQuery,
  useGetBusinessQuery,
  useGetBusinessCategoryQuery,
  useGetBusinessHoursQuery,
  useGetBusinessServicesQuery,
  useGetCategoriesQuery,
  useGetCategoryQuery,
  useGetServiceQuery,
  useGetServicesQuery,
  useGetBusinessEventsQuery,
  useGetBusinessEventSummaryQuery,
  useGetBusinessEventPeopleQuery,
  useGetBusinessUsersQuery,
  useGetBusinessEventTransactionsQuery,

  //Lazy Query hooks
  useLazyGetBusinessEventTransactionsQuery,
  useLazyGetBusinessUsersQuery,
  useLazyGetBusinessEventPeopleQuery,
  useLazyGetCategoryQuery,
  useLazyGetCategoriesQuery,
  useLazyGetAdminMobileQuery,
  useLazyGetServiceQuery,
  useLazyGetServicesQuery,
  useLazyGetAllBusinessClientsQuery,
  useLazyGetBusinessEventsQuery,
  useLazyGetBusinessQuery,
  useLazyGetBusinessCategoryQuery,
  useLazyGetBusinessHoursQuery,
  useLazyGetBusinessServicesQuery,
  useLazyGetBusinessEventSummaryQuery,
} = shortwaitsApi;
