import { EventStatusName } from "@shortwaits/shared-lib";
import { ThemeColorName } from "../theme/Colors";

// these are the available/remaining statues for each event status
export const nextEventStatuses: Record<EventStatusName, EventStatusName[]> = {
  PENDING: ["CANCELED", "REJECTED", "APPROVED"],
  APPROVED: ["CANCELED", "COMPLETED"],
  REJECTED: [],
  CANCELED: [],
  COMPLETED: [],
};

export const eventStatusIconNames: Record<EventStatusName, string> = {
  PENDING: "clock-outline",
  APPROVED: "check-circle-outline",
  REJECTED: "close-circle-outline",
  CANCELED: "cancel",
  COMPLETED: "check-circle-outline",
};

export const eventStatusColors: Record<EventStatusName, { color: ThemeColorName; backgroundColor: ThemeColorName }> = {
  PENDING: { color: "text", backgroundColor: "lightGray" },
  APPROVED: { color: "success", backgroundColor: "successBackground" },
  REJECTED: { color: "failed", backgroundColor: "failedBackground" },
  CANCELED: { color: "cancel", backgroundColor: "cancelBackground" },
  COMPLETED: { color: "white", backgroundColor: "success" },
};

export const eventStatusNames: Record<EventStatusName, string> = {
  PENDING: "pending",
  APPROVED: "accept",
  REJECTED: "reject",
  CANCELED: "cancel",
  COMPLETED: "complete",
};

export const CALENDAR_EVENT_HEIGHT = 75;
export const EVENT_ITEM_BORDER_RADIUS = 6;

export const STATIC_FORM_USA_STATES = [
  { title: "Alabama", _id: "AL" },
  { title: "Alaska", _id: "AK" },
  { title: "Arizona", _id: "AZ" },
  { title: "Arkansas", _id: "AR" },
  { title: "California", _id: "CA" },
  { title: "Colorado", _id: "CO" },
  { title: "Connecticut", _id: "CT" },
  { title: "Delaware", _id: "DE" },
  { title: "Florida", _id: "FL" },
  { title: "Georgia", _id: "GA" },
  { title: "Hawaii", _id: "HI" },
  { title: "Idaho", _id: "ID" },
  { title: "Illinois", _id: "IL" },
  { title: "Indiana", _id: "IN" },
  { title: "Iowa", _id: "IA" },
  { title: "Kansas", _id: "KS" },
  { title: "Kentucky", _id: "KY" },
  { title: "Louisiana", _id: "LA" },
  { title: "Maine", _id: "ME" },
  { title: "Maryland", _id: "MD" },
  { title: "Massachusetts", _id: "MA" },
  { title: "Michigan", _id: "MI" },
  { title: "Minnesota", _id: "MN" },
  { title: "Mississippi", _id: "MS" },
  { title: "Missouri", _id: "MO" },
  { title: "Montana", _id: "MT" },
  { title: "Nebraska", _id: "NE" },
  { title: "Nevada", _id: "NV" },
  { title: "New Hampshire", _id: "NH" },
  { title: "New Jersey", _id: "NJ" },
  { title: "New Mexico", _id: "NM" },
  { title: "New York", _id: "NY" },
  { title: "North Carolina", _id: "NC" },
  { title: "North Dakota", _id: "ND" },
  { title: "Ohio", _id: "OH" },
  { title: "Oklahoma", _id: "OK" },
  { title: "Oregon", _id: "OR" },
  { title: "Pennsylvania", _id: "PA" },
  { title: "Rhode Island", _id: "RI" },
  { title: "South Carolina", _id: "SC" },
  { title: "South Dakota", _id: "SD" },
  { title: "Tennessee", _id: "TN" },
  { title: "Texas", _id: "TX" },
  { title: "Utah", _id: "UT" },
  { title: "Vermont", _id: "VT" },
  { title: "Virginia", _id: "VA" },
  { title: "Washington", _id: "WA" },
  { title: "West Virginia", _id: "WV" },
  { title: "Wisconsin", _id: "WI" },
  { title: "Wyoming", _id: "WY" },
];

export const STATIC_FORM_AMERICAN_COUNTRIES = [
  { title: "United States", key: "US" },
  { title: "Antigua and Barbuda", key: "AG" },
  { title: "Argentina", key: "AR" },
  { title: "Bahamas", key: "BS" },
  { title: "Barbados", key: "BB" },
  { title: "Belize", key: "BZ" },
  { title: "Bolivia", key: "BO" },
  { title: "Brazil", key: "BR" },
  { title: "Canada", key: "CA" },
  { title: "Chile", key: "CL" },
  { title: "Colombia", key: "CO" },
  { title: "Costa Rica", key: "CR" },
  { title: "Cuba", key: "CU" },
  { title: "Dominica", key: "DM" },
  { title: "Dominican Republic", key: "DO" },
  { title: "Ecuador", key: "EC" },
  { title: "El Salvador", key: "SV" },
  { title: "Grenada", key: "GD" },
  { title: "Guatemala", key: "GT" },
  { title: "Guyana", key: "GY" },
  { title: "Haiti", key: "HT" },
  { title: "Honduras", key: "HN" },
  { title: "Jamaica", key: "JM" },
  { title: "Mexico", key: "MX" },
  { title: "Nicaragua", key: "NI" },
  { title: "Panama", key: "PA" },
  { title: "Paraguay", key: "PY" },
  { title: "Peru", key: "PE" },
  { title: "Saint Kitts and Nevis", key: "KN" },
  { title: "Saint Lucia", key: "LC" },
  { title: "Saint Vincent and the Grenadines", key: "VC" },
  { title: "Suriname", key: "SR" },
  { title: "Trinidad and Tobago", key: "TT" },
  { title: "Uruguay", key: "UY" },
  { title: "Venezuela", key: "VE" },
];
