import { businessSlice } from "./business-slice";

export const {
  setBusiness,
  setBusinessServicesFromDefault,
  setBusinessAllHours,
  setBusinessShortName,
  setBusinessDescription,
  setBusinessCurrency,
  setBusinessCountry,
  setBusinessPhone1,
  setBusinessWeekSchedule,
  setBusinessDaySchedule,
  setBusinessDayActivity,
  setBusinessLocation,
  setBusinessCategories,
  setBusinessCategory,
  setBusinessStaff,
  setBusinessService,
  setBusinessServices,
  setBusinessIsRegistrationCompleted,
  setBusinessDeleted,
  resetBusiness,
  setBusinessDayHours,
} = businessSlice.actions;
