import { shortwaitsApi } from "../shortwaits-api";

export const {
  //Mutations hooks
  useCreateEventMutation,
  useRegisterBusinessMutation,
  useLocalSignUpMutation,
  useLocalSignInMutation,
  useUpdateBusinessMutation,
  useUpdateBusinessServicesMutation,
  useUpdateBusinessHoursMutation,
  useCreateBusinessClientsMutation,
  useCreateBusinessStaffMutation,
  //Query hooks
  useGetAdminMobileQuery,
  useGetBusinessClientsQuery,
  useGetBusinessQuery,
  useGetBusinessCategoryQuery,
  useGetBusinessHoursQuery,
  useGetBusinessServicesQuery,
  useGetBusinessStaffQuery,
  useGetCategoriesQuery,
  useGetCategoryQuery,
  useGetServiceQuery,
  useGetServicesByBusinessQuery,
  useGetUserQuery,
  useGetEventsByBusinessQuery,
  //Lazy Query hooks
  useLazyGetUserQuery,
  useLazyGetCategoryQuery,
  useLazyGetCategoriesQuery,
  useLazyGetAdminMobileQuery,
  useLazyGetServiceQuery,
  useLazyGetServicesByBusinessQuery,
  useLazyGetBusinessClientsQuery,
  useLazyGetEventsByBusinessQuery,
  useLazyGetBusinessQuery,
  useLazyGetBusinessCategoryQuery,
  useLazyGetBusinessHoursQuery,
  useLazyGetBusinessServicesQuery,
  useLazyGetBusinessStaffQuery,
} = shortwaitsApi;
